from pathlib import Path

D = "d" + "iv"
p = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "app"
    / "portfolio"
    / "[id]"
    / "page.tsx"
)

lines = [
    '"use client";',
    "",
    'import { useEffect, useState } from "react";',
    'import { useParams } from "next/navigation";',
    "",
    'import { api } from "@/lib/api";',
    'import { num, pct, usd } from "@/lib/format";',
    'import type { Holding, PnlSummary, Portfolio } from "@/lib/types";',
    "",
    "export default function PortfolioOverviewPage() {",
    "  const id = String(useParams().id);",
    "  const [portfolio, setPortfolio] = useState<Portfolio | null>(null);",
    "  const [holdings, setHoldings] = useState<Holding[]>([]);",
    "  const [pnl, setPnl] = useState<PnlSummary | null>(null);",
    "  const [loading, setLoading] = useState(true);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  useEffect(() => {",
    '    if (!id || id === "undefined") return;',
    "    setLoading(true);",
    "    setError(null);",
    "    Promise.all([",
    "      api.get<Portfolio>(`/portfolios/${id}`),",
    "      api.get<Holding[]>(`/portfolios/${id}/holdings`).catch(() => [] as Holding[]),",
    "      api.get<PnlSummary>(`/portfolios/${id}/pnl`).catch(() => null),",
    "    ])",
    "      .then(([p, h, pnlRes]) => {",
    "        setPortfolio(p);",
    "        setHoldings(Array.isArray(h) ? h : []);",
    "        setPnl(pnlRes);",
    "      })",
    "      .catch((err) => {",
    "        setPortfolio(null);",
    '        setError(String(err).replace(/^Error: /, ""));',
    "      })",
    "      .finally(() => setLoading(false));",
    "  }, [id]);",
    "",
    '  if (loading) return <p className="alert alert-info">Loading overview…</p>;',
    "  if (error) {",
    "    return (",
    '      <div className="alert alert-error">',
    "        {error}",
    '        <p className="mt-2 text-sm text-white/50">',
    "          Sign in again or open from dashboard.",
    "        </p>",
    f"      </{D}>",
    "    );",
    "  }",
    "  if (!portfolio) {",
    f'    return <{D} className="alert alert-warning">Portfolio not found.</{D}>;',
    "  }",
    "  return (",
    '    <section className="space-y-6">',
    f'      <{D} className="grid grid-cols-2 md:grid-cols-4 gap-3">',
    f'        <{D} className="metric-card">',
    '          <p className="text-xs text-white/40">Starting capital</p>',
    '          <p className="text-lg font-semibold text-white">{usd(portfolio.starting_capital)}</p>',
    f"        </{D}>",
    f'        <{D} className="metric-card">',
    '          <p className="text-xs text-white/40">Cost basis</p>',
    '          <p className="text-lg font-semibold text-white">{portfolio.cost_basis_method ?? "fifo"}</p>',
    f"        </{D}>",
    f'        <{D} className="metric-card">',
    '          <p className="text-xs text-white/40">Realized PnL</p>',
    '          <p className="text-lg font-semibold text-white">{pnl ? usd(pnl.realized_pnl) : "—"}</p>',
    f"        </{D}>",
    f'        <{D} className="metric-card">',
    '          <p className="text-xs text-white/40">Unrealized PnL</p>',
    '          <p className="text-lg font-semibold text-white">{pnl ? usd(pnl.unrealized_pnl) : "—"}</p>',
    f"        </{D}>",
    f"      </{D}>",
    "      {pnl && (pnl.total_return_twr != null || pnl.total_return_mwr != null) ? (",
    f'        <{D} className="grid grid-cols-2 md:grid-cols-3 gap-3">',
    f'          <{D} className="metric-card"><p className="text-xs text-white/40">TWR</p><p className="text-lg font-semibold text-white">{{pct(pnl.total_return_twr)}}</p></{D}>',
    f'          <{D} className="metric-card"><p className="text-xs text-white/40">MWR</p><p className="text-lg font-semibold text-white">{{pct(pnl.total_return_mwr)}}</p></{D}>',
    f'          <{D} className="metric-card"><p className="text-xs text-white/40">Dividend income</p><p className="text-lg font-semibold text-white">{{usd(pnl.dividend_income)}}</p></{D}>',
    f"        </{D}>",
    "      ) : null}",
    "      <section>",
    '        <h2 className="text-lg font-semibold text-white mb-3">Holdings (from transactions)</h2>',
    "        {holdings.length === 0 ? (",
    f'          <{D} className="alert alert-info">No holdings yet. Add a BUY transaction.</{D}>',
    "        ) : (",
    '          <table className="data-table">',
    "            <thead><tr><th>Ticker</th><th>Quantity</th><th>Avg cost</th><th>Market value</th><th>Unrealized PnL</th></tr></thead>",
    "            <tbody>",
    "              {holdings.map((h) => (",
    "                <tr key={h.ticker}>",
    '                  <td className="font-mono text-white">{h.ticker}</td>',
    "                  <td>{num(h.quantity)}</td>",
    "                  <td>{usd(h.avg_cost)}</td>",
    "                  <td>{usd(h.market_value)}</td>",
    "                  <td>{usd(h.unrealized_pnl)}</td>",
    "                </tr>",
    "              ))}",
    "            </tbody>",
    "          </table>",
    "        )}",
    "      </section>",
    "    </section>",
    "  );",
    "}",
    "",
]

p.write_text("\n".join(lines), encoding="utf-8")
print("wrote", p)
